apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-argocd
  namespace: myargo
spec:
  project: default
  source:
    repoURL: https://github.com/litnguyen/argocd-deployment.git
    targetRevision: HEAD
    path: ./
  destination:
    server: https://kubernetes.default.svc
    namespace: myargo
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
